export const PamlightConstants = {
    CLIENT_VERIFY_SOCKET: '_VERIFY_SOCKET_STATUS_',
    CLIENT_SOCKET_VERIFICATION_SUCCESS: 'CLIENT_SOCKET_VERIFICATION_SUCCESS',
    CLIENT_SOCKET_VERIFICATION_ERROR: 'CLIENT_SOCKET_VERIFICATION_ERROR',
    CLIENT_SOCKET_RECONNECTION_TRIGGER: 'CLIENT_SOCKET_RECONNECTION_TRIGGER',
    CLIENT_SOCKET_API_ACTION: 'CLIENT_SOCKET_API_ACTION',

    ADMIN_VERIFY_SOCKET: 'ADMIN_VERIFY_SOCKET',
    ADMIN_SOCKET_VERIFIED: 'ADMIN_SOCKET_VERIFIED',
    ADMIN_SOCKET_VERIFY_ERROR: 'ADMIN_SOCKET_VERIFY_ERROR',
    ADMIN_SOCKET_API_ACTION: 'ADMIN_SOCKET_API_ACTION',
    ADMIN_SOCKET_GET_QUERY: 'ADMIN_SOCKET_GET_QUERY',
    ADMIN_SOCKET_WRITE_CONFIG: 'ADMIN_SOCKET_WRITE_CONFIG',

    UTILITIES_SERVER_TIME: 'UTILITIES_SERVER_TIME',
    UTILITIES_VALIDATE_SYNC: 'UTILITIES_VALIDATE_SYNC'
};
